[package]
name = "my-package"
version.workspace = true
edition.workspace = true

[[bin]]
path = "src/main.rs"
name = "my-app"

[dependencies]
git-package = { git = "https://github.com/mkatychev/crane_build_rs", rev = "cfc475c" }
